CosmosOS/IL2CPU

- source/Cosmos.IL2CPU/IL/Newobj.cs
Copied from https://github.com/CosmosOS/Cosmos/pull/692
There's no easy way to test this, as tests will hit other bugs, but https://github.com/CosmosOS/Cosmos/pull/692 has a simple test that proves that this works and I spent a lot of time debugging this in Bochs, so I'm sure it has the correct behaviour.
> Newobj fix

- source/Cosmos.IL2CPU/ILOpCodes/OpNone.cs
- Implement **Stelem_R4** case in `OpNone.cs` since it does exist
- Implement **Stelem_R8** case in `OpNone.cs` since it does exist
```csharp
float[] mFloat = new float[16];
mFloat[5] = 0.28301;
mFloat[6] = 0.2894;
mFloat[11] = mFloat[5] + mFloat[6];
Console.WriteLine(mFloat[11]);
double[] mDouble = new double[16];
mDouble[5] = 0.28301;
mDouble[6] = 0.2894;
mDouble[11] = mDouble[5] + mDouble[6];
Console.WriteLine(mDouble[11]);
Console.ReadKey(true);
```
> Fix Double Arrays

- source/Cosmos.IL2CPU/IL/Not.cs
- source/Cosmos.IL2CPU/IL/Xor.cs
Changes from https://github.com/CosmosOS/Cosmos/pull/674
- Implemented Xor and Not for 8 byte operands.
- Optimized Xor and Not for 4 byte operands.
> Xor and Not fixes

- source/Cosmos.IL2CPU/IL/Callvirt.cs
- Fixed `callvirt` for boxed value types.
> Callvirt fixes

- source/Cosmos.IL2CPU/IL/Ldfld.cs
- source/Cosmos.IL2CPU/IL/Newobj.cs
- source/Cosmos.IL2CPU/ILOp.cs
- source/Cosmos.IL2CPU/ILOpCodes/OpType.cs
- tests/IL2CPU.Compiler.Tests/IL2CPU.Compiler.Tests.csproj
- tests/IL2CPU.Compiler.Tests/ILOpTests.cs
Fixes #12.
- Added missing calculations for struct fields.
- Fixed `ldfld` and `newobj`.
- Fixed stack push type for box in `OpType`.
- Added tests.
> Fixed value type field offset and size calculations

- source/Cosmos.IL2CPU/IL/Unaligned.cs
- source/Cosmos.IL2CPU/ILOpCodes/OpInt.cs
- source/Cosmos.IL2CPU/ILReader.cs
- Added support for `Unsafe` intrinsics.
This is not really the correct way of implementing it, but it avoids many plugs. On .NET Core 2.1, intrinsics are marked with the `Intrinsic` attribute, on .NET Core 2.0 we have to check the type namespace and name and implement the IL instructions for it. As there are two `Unsafe` implementations (one on coreclr and the other one on corefx), we can just pull the body of the corefx methods and replace the body of the coreclr ones for now.
> Added support for Unsafe intrinsics

- source/Cosmos.IL2CPU/VTablesImpl.cs
- Changed `VTable` struct layout to sequential, as the struct contains reference fields, so now it's portable between different architectures.
Cosmos CI build: https://ci.appveyor.com/project/CosmosOS/cosmos/build/0.20150918.2106
> Changed VTable struct layout to sequential

- source/Cosmos.IL2CPU/IL/Callvirt.cs
- Fixed `callvirt` for boxed value types.
> Fixed callvirt for boxed value types

- source/Cosmos.IL2CPU/Cosmos.IL2CPU.csproj
- source/Cosmos.IL2CPU/IL/Ldobj.cs
- source/Cosmos.IL2CPU/ILReader.cs
Included System.Runtime.CompilerServices.Unsafe
Fixed handling of unsafe methods in ILReader for unsafe methods
This PR also fixes Ldobj to correctly handle sign extension
> Allow usage of Unsafe

- source/Cosmos.IL2CPU/IL/Add_Ovf.cs
- source/Cosmos.IL2CPU/IL/Add_Ovf_Un.cs
- source/Cosmos.IL2CPU/IL/Sub_Ovf.cs
- source/Cosmos.IL2CPU/IL/Sub_Ovf_Un.cs
- source/Cosmos.IL2CPU/ILOpCodes/OpNone.cs
I added the Sub_Ovh Implementation next is the Sub_Ovh_Un Implementation this is for ticket: #9
> Added Sub_Ovh implementation.

- source/Cosmos.IL2CPU/ILOpCode.cs
- source/Cosmos.IL2CPU/ILOpCodes/OpBranch.cs
An unconditional branch will never not branch, so we dont interpret stack if we didnt branch (as done for other branches. Otherwise, this can lead to bugs, as the opcode after an unconditional branch is reached via a jump with a different stack, than the one in the block ending with the unconditional branch before. Can be reproduced by trying to compile this code: `char c2 = (c <= 'Z' && c >= 'A') ? ((char)(c - 65 + 97)) : c;`
> Fix unconditional branch stack corruption

- source/Cosmos.IL2CPU/IL/Ldstr.cs
Fixes stack corruptions introduced by #93 due to strings with backslashes marking lines as comments in NASM, which prevented them from compiling, leading to incorrect asm being emitted for ldstr.
> Fix stack corruptions due to incorrect NASM comments 

- source/Cosmos.IL2CPU/AppAssembler.cs
Fixed running analysis to check if instructions have been fully processed before the instructions have started to be processed
> Too eager checks when interpreting stack

- source/Cosmos.IL2CPU/CompilerEngine.cs
Fixes IL2CPU crash when the VBE parameters are missing in the .csproj file
> Ignore missing VBE flag in csproj during compile

- source/Cosmos.IL2CPU/VTablesImplRefs.cs
- source/IL2CPU.API/ObjectUtils.cs
Clean up object utils
Required for delegates with return types
> Add IsStruct to VTablesImpl

- source/Cosmos.IL2CPU/AppAssembler.cs
- source/Cosmos.IL2CPU/CompilerEngine.cs
- source/Cosmos.IL2CPU/ConsoleCompilerEngineSettings.cs
- source/Cosmos.IL2CPU/CosmosAssembler.cs
- source/Cosmos.IL2CPU/ICompilerEngineSettings.cs
If the option enabled the compiler run faster,
The fast boost also remove more than 1000 lines of code in the final asm file
> Added Remove Debug Output Option

- source/Cosmos.IL2CPU/ConsoleCompilerEngineSettings.cs
> Get the full path for an assembly reference

- source/Cosmos.IL2CPU/AppAssembler.cs
- source/Cosmos.IL2CPU/IL/Call.cs
- source/Cosmos.IL2CPU/ILOp.cs
- source/Cosmos.IL2CPU/ILScanner.cs
- source/Cosmos.IL2CPU/PlugManager.cs
Plugs will only call the trampoline code when required. When possible just change all calls to go the plug directly
> Reduce usage of plug trampoline code

- source/Cosmos.IL2CPU/CompilerEngine.cs
- source/Cosmos.IL2CPU/ConsoleCompilerEngineSettings.cs
- source/Cosmos.IL2CPU/ICompilerEngineSettings.cs
This PR adds a CLI argument to IL2CPU to disable X# comments. A Cosmos PR will come soon to add this argument to the build tasks as well, so that they can be enabled.
> Add CLI argument to disable X# comments

- source/Cosmos.IL2CPU/AppAssembler.cs
- source/Cosmos.IL2CPU/CompilerEngine.cs
- tests/IL2CPU.Compiler.Tests/ILStackAnalysisTests.cs
Fixes ManifestResourceStreams speed using the `incbin` NASM/YASM assembler directive. This includes binary directly from an external file which is a lot faster than using a huge `db` instruction.
30mb file:
```
Before:
1>IL2CPU task took 00:00:36.5974656
1>-g dwarf2 -f elf -o bin\Debug\net6.0\nxtlvlOS.obj -dELF_COMPILATION -O2 bin\Debug\net6.0\nxtlvlOS.asm
1>Yasm task took 00:06:10.1939569
```
```
After:
1>IL2CPU task took 00:00:23.8534121
1>-g dwarf2 -f elf -o bin\Debug\net6.0\nxtlvlOS.obj -dELF_COMPILATION -O2 bin\Debug\net6.0\nxtlvlOS.asm
1>Yasm task took 00:00:10.8834183
```
> Fix ManifestResourceStream speed: Use assembler directive `incbin` instead of outputting the binary to the asm output

- source/Cosmos.IL2CPU/ILScanner.cs
Removed the newline and added a note that you should check the build output for more information, hopefully reducing the amount of "Getting useless System.Exception" blablabla issues and discord threads
> Improve error message for missing plugs

- source/IL2CPU.Debug.Symbols/SqliteBulkCopy.cs
This fixes the crash as shown in #204
> Fix random crash (#204)

- source/Cosmos.IL2CPU/IL/Ldfld.cs
- source/Cosmos.IL2CPU/IL/Stfld.cs
The issue was that we were pushing the remainder at the end when loading, this caused the values to be aligned differently after a ldfld.
> Fix loading of packed structure

- source/IL2CPU.Debug.Symbols/DebugInfo.cs
As counter productive as this may seem, this weirdly seems to improve performance.
In my case, I ran the first test in the default TestKernelSet. Previously, it took around 12.3s, with these changes it only takes 10.6s-10.7s
nxtlvlOS compilation went from 22.1s to 20.7s
> Reduce SqliteBulkCopy flush size
