CosmosOS/IL2CPU

source/Cosmos.IL2CPU/ILOpCodes/OpBranch.cs
Added Compare to Int and Bool | Bool and Int
Fix https://github.com/CosmosOS/Cosmos/issues/722
=> Fix switch with Boolean

source/Cosmos.IL2CPU/IL/Throw.cs
=> Throw op cleanup

source/Cosmos.IL2CPU/IL/Conv_I.cs, source/Cosmos.IL2CPU/IL/Conv_I1.cs, source/Cosmos.IL2CPU/IL/Conv_I2.cs, source/Cosmos.IL2CPU/IL/Conv_I4.cs, source/Cosmos.IL2CPU/IL/Conv_I8.cs, source/Cosmos.IL2CPU/IL/Conv_R4.cs, source/Cosmos.IL2CPU/IL/Conv_R8.cs, source/Cosmos.IL2CPU/IL/Conv_R_Un.cs, source/Cosmos.IL2CPU/IL/Conv_U.cs, source/Cosmos.IL2CPU/IL/Conv_U1.cs, source/Cosmos.IL2CPU/IL/Conv_U2.cs, source/Cosmos.IL2CPU/IL/Conv_U4.cs, source/Cosmos.IL2CPU/IL/Conv_U8.cs
- Fixed and optimized Conv ops.
=> Conv fixes

source/Cosmos.IL2CPU/Cosmos.IL2CPU.csproj, source/IL2CPU.Debug.Symbols/IL2CPU.Debug.Symbols.csproj
- Package upgrades and downgrades, required by the new project system.
**Has to be merged right before CosmosOS/Cosmos#839.**
=> Package version changes

source/Cosmos.IL2CPU/IL/Branch.cs
=> Branch fixes

source/Cosmos.IL2CPU/IL/Div.cs, source/Cosmos.IL2CPU/IL/Rem.cs
- Fixed `div` and `rem` for `int64` operands.
=> Fixed div and rem for int64 operands

source/Cosmos.IL2CPU/IL/Castclass.cs, source/Cosmos.IL2CPU/IL/Isinst.cs, source/Cosmos.IL2CPU/IL/Unbox.cs, source/Cosmos.IL2CPU/IL/Unbox_Any.cs, source/Cosmos.IL2CPU/VTablesImpl.cs
- Added support for interfaces to IsInstance.
Tests: CosmosOS/Cosmos#930
=> Added support for interfaces to IsInstance

source/Cosmos.IL2CPU/IL/Callvirt.cs
=> Callvirt fix

source/Cosmos.IL2CPU/IL/Unbox.cs, source/Cosmos.IL2CPU/IL/Unbox_Any.cs
=> Fixed unbox

source/Cosmos.IL2CPU/ILOpCodes/OpBranch.cs
Combined interface and class check.
=> CosmosOS Comparer Issue #584

source/Cosmos.IL2CPU/IL/Cgt.cs
=> Fix Cgt for long

source/Cosmos.IL2CPU/IL/Ldarg.cs, tests/IL2CPU.Compiler.Tests/LdArgTests.cs
Fixed bug when return size is larger than the argument size
Also added tests
=> Fixed argument displacement calculations

source/Cosmos.IL2CPU/ILOpCode.cs
Fixes https://github.com/CosmosOS/Cosmos/issues/1246
=> Fix handling of enums as integer type

source/Cosmos.IL2CPU/AppAssembler.cs, source/Cosmos.IL2CPU/ILOpCode.cs, source/Cosmos.IL2CPU/ILOpCodes/OpBranch.cs, source/Cosmos.IL2CPU/ILOpCodes/OpSwitch.cs
Caused by https://github.com/CosmosOS/IL2CPU/pull/94
=> Fixed incomplete stack interpretation

source/Cosmos.IL2CPU/ILScanner.cs
Fix crash when more than one possible method is found
=> Fix ILScanner problem

source/Cosmos.IL2CPU/IL/Readonly.cs
It should be fine for now to do nothing in readonly
=> Implement readonly

source/Cosmos.IL2CPU/IL/Newobj.cs, source/IL2CPU.API/LabelName.cs
Fix string ctor allocating too litlle space
Fix method collision
=> Bug fixes for net 5

source/Cosmos.Core.DebugStub/Cosmos.Core.DebugStub.csproj, source/Cosmos.IL2CPU/AppAssembler.cs, source/Cosmos.IL2CPU/Cosmos.IL2CPU.csproj, source/Cosmos.IL2CPU/IL/Ldflda.cs, source/IL2CPU.API/IL2CPU.API.csproj, source/IL2CPU.Debug.Symbols/DebugInfo.cs, source/IL2CPU.Debug.Symbols/IL2CPU.Debug.Symbols.csproj, source/IL2CPU.Debug.Symbols/ObjDump.cs, source/IL2CPU/IL2CPU.csproj
Necessary changes to work with unit tests in cosmos
Optimized compilation time
=> Further fixes for net 5

build/Targets/InternalPackages.targets
=> Update XSharp path

source/Cosmos.IL2CPU/CosmosAssembler.cs, source/Cosmos.IL2CPU/GCImplementationRefs.cs, source/Cosmos.IL2CPU/ILOp.cs, source/Cosmos.IL2CPU/ILOpCodes/OpField.cs, source/Cosmos.IL2CPU/ILOpCodes/OpNone.cs, source/Cosmos.IL2CPU/ILScanner.cs
=> Revert "Memory manager"

source/Cosmos.IL2CPU/CompilerEngine.cs, source/Cosmos.IL2CPU/ConsoleCompilerEngineSettings.cs, source/Cosmos.IL2CPU/CosmosAssembler.cs, source/Cosmos.IL2CPU/ICompilerEngineSettings.cs
Needed by https://github.com/CosmosOS/Cosmos/pull/1995
=> Add VBE compilation in multiboot structure

source/Cosmos.IL2CPU/AppAssembler.cs
Check that the field has the correct type
=> Improve ManifestResourceStream Compilation

source/Cosmos.IL2CPU/AppAssembler.cs, source/Cosmos.IL2CPU/CompilerEngine.cs, source/Cosmos.IL2CPU/ILOp.cs, source/Cosmos.IL2CPU/PlugManager.cs, source/Cosmos.IL2CPU/_MethodInfo.cs
Add some optimizations to IL2CPU.
=> Add optimizations

source/IL2CPU.Debug.Symbols/IL2CPU.Debug.Symbols.csproj
Fix build for [https://ci.appveyor.com/project/CosmosOS/cosmos/builds/41605896](https://ci.appveyor.com/project/CosmosOS/cosmos/builds/41605896)
=> Undo "Fix/debug symbols target"

source/Cosmos.IL2CPU/CosmosAssembler.cs
Needs https://github.com/CosmosOS/XSharp/pull/55
Todo:
Resources:
https://www.gnu.org/software/grub/manual/multiboot2/multiboot.html
=> Implement multiboot2

source/Cosmos.IL2CPU/CosmosAssembler.cs
Fix for https://github.com/CosmosOS/Cosmos/pull/2017
=> Align constants + stack to 16

source/Cosmos.IL2CPU/CosmosAssembler.cs
Fix for https://github.com/CosmosOS/Cosmos/pull/2017
=> Remove useless fields + call Multiboot2Init

source/IL2CPU.Debug.Symbols.Net48/IL2CPU.Debug.Symbols.Net48.csproj, source/IL2CPU.Debug.Symbols/SQL.cs
Fix how sql files are included in the net48 csproj to match the normal csproj
Improve error message in SQL.cs
=> Fix embedded resources in IL2CPU.Debug.Symbols.Net48.csproj

source/Cosmos.IL2CPU/ILOpCodes/OpField.cs
Thanks to Terminal.cs for finding this issue.
=> Fix Ldflda stack analysis

source/IL2CPU.API/LabelName.cs
PrivateImplementationDetails is also part of multiple assemblies
=> Add PrivateImplementationDetails to the cases

source/IL2CPU.Debug.Symbols.Net48/IL2CPU.Debug.Symbols.Net48.csproj, source/IL2CPU.Debug.Symbols/IL2CPU.Debug.Symbols.csproj
Replace Microsoft.Data.Sqlite by Microsoft.Data.Sqlite.Core
=> Fix map file generation

source/Cosmos.IL2CPU/AppAssembler.cs, source/Cosmos.IL2CPU/IL/Call.cs, source/Cosmos.IL2CPU/IL/Ldarg.cs, source/Cosmos.IL2CPU/IL/Ldstr.cs, source/Cosmos.IL2CPU/ILOp.cs
Also prevent multiple string literals for same value (Decrease number of emitted string literals by ~30%)
Also cleans up code + fix space/tab issues
=> Support delegates with return value

source/Cosmos.IL2CPU/ILOpCodes/.editorconfig, source/Cosmos.IL2CPU/ILOpCodes/OpField.cs
Removed editotconfig file and reformatted to 4 spaces
=> Allow ldfld to allow loading from unmanaged pointer (native int)

source/Cosmos.IL2CPU/IL/Newarr.cs
=> Fix newarr determining incorrect element types

source/Cosmos.IL2CPU/AppAssembler.cs, source/Cosmos.IL2CPU/Cosmos.IL2CPU.csproj, source/Cosmos.IL2CPU/ILOp.cs, source/Cosmos.IL2CPU/ILOpCode.cs, source/Cosmos.IL2CPU/PlugManager.cs, source/IL2CPU.Debug.Symbols/DebugInfo.cs, source/IL2CPU.Debug.Symbols/DebugSymbolReader.cs, source/IL2CPU.Debug.Symbols/ObjDump.cs
Missing nops were causing instructions to be replaced
Also fixes the way sql connections for debug data are managed
=> Fix debug nop emitting

Directory.Build.props
This is required to fix the current build issues
=> Bump Cosmos.Build.Common Version

source/Cosmos.IL2CPU/MethodAnalysis/ILGroup.cs, tests/IL2CPU.Compiler.Tests/ILStackAnalysisTests.cs
Fixed il stack analysis tests and added new case
Fixes https://github.com/CosmosOS/Cosmos/issues/2453
=> Fix crash when the final opcode in the method has some following opcode

source/Cosmos.IL2CPU/AppAssembler.cs, source/Cosmos.IL2CPU/CompilerEngine.cs, source/Cosmos.IL2CPU/CosmosAssembler.cs, source/Cosmos.IL2CPU/IL/Nop.cs, source/Cosmos.IL2CPU/ILScanner.cs, source/Cosmos.IL2CPU/PlugManager.cs, source/IL2CPU.API/LabelName.cs
Fixes https://github.com/CosmosOS/IL2CPU/issues/150 and https://github.com/CosmosOS/Cosmos/issues/2619
=> Improve label generation

source/Cosmos.IL2CPU/CompilerEngine.cs, source/Cosmos.IL2CPU/ILOp.cs, source/IL2CPU.Debug.Symbols/DebugInfo.cs
This PR aims to improve IL2CPU performance a bit. With my changes, IL2CPU time went from 26.4s to 22.1s on [this repo](https://github.com/GoldenretriverYT/nxtlvlOS) after focusing on some of the hotspots I found with dotTrace.
=> Speed up IL2CPU slightly

README.md
=> update site link in read me
